#!/usr/bin/env python

import sys
import os
import re

# Issue 529: google/protobuf/compiler/__init__.py is missing.
# Until it is fixed, we need to help Python import plugin_pb2.
try:
    from google.protobuf.compiler.plugin_pb2 import CodeGeneratorRequest, \
            CodeGeneratorResponse
except ImportError:
    import google.protobuf
    sys.path.append(os.path.join(google.protobuf.__path__[0], "compiler"))
    from plugin_pb2 import CodeGeneratorRequest, CodeGeneratorResponse


serialized = sys.stdin.read()
req = CodeGeneratorRequest()
req.ParseFromString(serialized)

resp = CodeGeneratorResponse()

for protofile in req.proto_file:
    insert = resp.file.add()
    fnparts = re.match("gen/(\w+).(\w+).proto", protofile.name).groups()
    if fnparts is not None:
        insert.name = "gen/%s/%s_pb2.py" % fnparts
    else:
        raise RuntimeError("Impossible to construct filename")
    insert.insertion_point = "module_scope"
    pbfn = "gen/%s.%s.pb" % fnparts
    with open(pbfn, 'r') as pbf:
        pb = pbf.read()
    insert.content = "_piqi_defn_pb=%s" % repr(pb)

sys.stdout.write(resp.SerializeToString())
